const PARCEL_STATUS = {
  CREATED: "CREATED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  OTP_SENT: "OTP_SENT",
  FAILED_ATTEMPT: "FAILED_ATTEMPT",
  DELIVERED: "DELIVERED",
  RETURNED: "RETURNED"
};


const ALLOWED_TRANSITIONS = {

  CREATED: [
    PARCEL_STATUS.OUT_FOR_DELIVERY
  ],

  OUT_FOR_DELIVERY: [
    PARCEL_STATUS.OTP_SENT,
    PARCEL_STATUS.RETURNED
  ],

  OTP_SENT: [
    PARCEL_STATUS.DELIVERED,
    PARCEL_STATUS.FAILED_ATTEMPT
  ],

  FAILED_ATTEMPT: [
    PARCEL_STATUS.OTP_SENT,
    PARCEL_STATUS.RETURNED
  ],

  DELIVERED: [],

  RETURNED: []
};


module.exports = {
  PARCEL_STATUS,
  ALLOWED_TRANSITIONS
};